# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build And Test

on:
  push:
    paths:
    - '**'

  pull_request:
    paths:
    - '**'
  
jobs:
  build:
    env:
      SA_PROJECT_ID: ${{ secrets.SA_PROJECT_ID }}
      SA_PRIVATE_KEY_ID: ${{ secrets.SA_PRIVATE_KEY_ID }}
      SA_PRIVATE_KEY: ${{ secrets.SA_PRIVATE_KEY }}
      SA_CLIENT_EMAIL: ${{ secrets.SA_CLIENT_EMAIL }}
      SA_CLIENT_ID: ${{ secrets.SA_CLIENT_ID }}
      SA_CLIENT_X509_CERT_URL: ${{ secrets.SA_CLIENT_X509_CERT_URL }}
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
      MONGODB_NAME: ${{ secrets.MONGODB_NAME }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Execute
      id: execute
      run: |
        python main.py upload_spreadsheet:no upload_mongodb:no