name: Get Japan BaseBall Results

on:
  schedule:
    - cron: '* */1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest requests gspread oauth2client python-decouple
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute
      env:
          SA_PROJECT_ID: ${{ secrets.SA_PROJECT_ID }}
          SA_PRIVATE_KEY_ID: ${{ secrets.SA_PRIVATE_KEY_ID }}
          SA_PRIVATE_KEY: ${{ secrets.SA_PRIVATE_KEY }}
          SA_CLIENT_EMAIL: ${{ secrets.SA_CLIENT_EMAIL }}
          SA_CLIENT_ID: ${{ secrets.SA_CLIENT_ID }}
          SA_CLIENT_X509_CERT_URL: ${{ secrets.SA_CLIENT_X509_CERT_URL }}
      run: |
        python baseball-japan/main.py from:complete_spreadsheet upload:yes